name: portfolio


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_page_transition: ^0.0.1+2
  typewritertext: ^1.8.0
  social_media_buttons: ^0.1.2
  hovering: ^1.0.4
  webview_flutter: ^2.0.14
  carousel_slider: ^4.1.1
  auto_size_text: ^3.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: abel
      fonts:
        - asset: assets/fonts/abel-regular.ttf